# -- Appearance ---------------------------------------------------------------

[font]
size = 16.0

[font.bold]
family = "Rec Mono Linear"
style = "Bold"

[font.bold_italic]
family = "Rec Mono Linear"
style = "Bold Italic"

[font.italic]
family = "Rec Mono Linear"
style = "Italic"

[font.normal]
family = "Rec Mono Linear"
style = "Regular"

[colors.primary]
# Quiet theme with synthwave highlights
background = "#0c0c0c"  # Very dark gray, softer than pure black
foreground = "#e4e4e4"  # Light gray foreground for readability

[colors.cursor]
cursor = "#ff00ff"

[colors.normal]
black = "#202020"       # Dark gray
red = "#cc8faa"         # Muted magenta/pink (from bright #ff0080)
green = "#8fcc9f"       # Muted green (from bright #00ff80)
yellow = "#ccb38f"      # Muted amber (from bright #ffb300)
blue = "#8fb3cc"        # Muted cyan-blue (from bright #00ccff)
magenta = "#cc8fcc"     # Muted magenta (from bright #ff00ff)
cyan = "#8fcccc"        # Muted cyan (from bright #00ffff)
white = "#b8b8b8"       # Medium gray

[colors.bright]
black = "#787878"       # Invisible gray
red = "#ff0080"         # Error red
green = "#00ff80"       # Bright green
yellow = "#ffb300"      # UI amber
blue = "#00ccff"        # UI blue
magenta = "#ff00ff"     # UI cur search
cyan = "#00ffff"        # UI teal
white = "#ffffff"       # Pure white

# -- Keybinds -----------------------------------------------------------------

[[keyboard.bindings]]
action = "ToggleFullscreen"
key = "Return"
mods = "Alt"

[[keyboard.bindings]]
action = "ToggleFullscreen"
key = "Return"
mods = "Command"

[window]
opacity = 0.95
decorations = "Full"
option_as_alt = "Both" # treat option as alt in mac os

[[keyboard.bindings]]
key = "1"
mods = "Command"
chars = "\u001b1"  # Alt+1

[[keyboard.bindings]]
key = "2"
mods = "Command"
chars = "\u001b2"  # Alt+2

[[keyboard.bindings]]
key = "N"
mods = "Command"
chars = "\u001bn"  # Alt+N

[[keyboard.bindings]]
key = "P"
mods = "Command"
chars = "\u001bp"  # Alt+P

[[keyboard.bindings]]
key = "D"
mods = "Command"
chars = "\u001bd"  # Alt+D

[[keyboard.bindings]]
key = "F"
mods = "Command"
chars = "\u001bf"  # Alt+F

[[keyboard.bindings]]
key = "B"
mods = "Command"
chars = "\u001bb"  # Alt+B

[[keyboard.bindings]]
key = "O"
mods = "Command"
chars = "\u001bo"  # Alt+O

[[keyboard.bindings]]
key = "K"
mods = "Command"
chars = "\u001bk"  # Alt+K
