# vim: set ft=conf
cursor-style = block
cursor-color = ff00ff
shell-integration-features = no-cursor
font-family = "Rec Mono Linear"
font-size = 16
cursor-style-blink = false
background-opacity = 0.95
title = " "
auto-update = off
window-height = 55
window-width = 100
macos-option-as-alt = true
# disable stupid link highlight when pressing ctrl
link-url = false

theme = dark:Carbonfox,light:Dawnfox
# theme = dark:Duskfox,light:Dawnfox

gtk-titlebar-hide-when-maximized = true

macos-non-native-fullscreen = padded-notch
macos-option-as-alt = true
macos-titlebar-proxy-icon = hidden

keybind = alt+enter=toggle_maximize
# does not seem to work?
# key-remap = cmd=left_alt
keybind = ctrl+shift+c=copy_to_clipboard
keybind = ctrl+shift+v=paste_from_clipboard
keybind = alt+c=copy_to_clipboard
keybind = alt+v=paste_from_clipboard

# this does work.. but not for <A-o>
keybind = super+Digit1=text:\x1b1
keybind = super+Digit2=text:\x1b2
keybind = super+Digit3=text:\x1b3
keybind = super+n=text:\x1bn
keybind = super+f=text:\x1bf
keybind = super+b=text:\x1bb
# this does not work but the others do
# keybind = super+o=text:\x1bo
keybind = super+t=text:\x1bt
keybind = super+c=text:\x1bt
