# vim: set ft=conf
background = 0a0a10
foreground = cdd6f4
cursor-color = ff00ff
font-family = "Rec Mono Linear"
font-size = 16
cursor-style-blink = false
background-opacity = 0.9
title = " "
auto-update = off

macos-non-native-fullscreen = padded-notch
macos-option-as-alt = true
macos-titlebar-proxy-icon = hidden

keybind = alt+enter=toggle_fullscreen
keybind = super+Digit1=text:\x1b1
keybind = super+Digit2=text:\x1b2
keybind = super+Digit3=text:\x1b3
