# vim: set ft=conf
cursor-style = block
cursor-color = ff00ff
shell-integration-features = no-cursor
font-family = "Rec Mono Linear"
font-size = 16
cursor-style-blink = false
background-opacity = 0.95
title = " "
auto-update = off
window-height = 55
window-width = 100
macos-option-as-alt = true
# disable stupid link highlight when pressing ctrl
link-url = false

theme = dark:Carbonfox,light:Dawnfox
# theme = dark:Duskfox,light:Dawnfox

gtk-titlebar-hide-when-maximized = true

macos-non-native-fullscreen = padded-notch
macos-option-as-alt = true
macos-titlebar-proxy-icon = hidden

keybind = alt+enter=toggle_maximize
key-remap = super=left_alt
