#- Spartan Tmux ---------------------------------------------------------------
set -g history-limit 250000
set -g status on
set -g lock-after-time 0
setw -g alternate-screen on
setw -g automatic-rename off
set -g allow-set-title off
set -g allow-rename off
set -gq utf-8 on
set -g set-clipboard external
# Alacritty is our terminal of choice, so we optimise for that.
set -g default-terminal "tmux-256color"
set -ag terminal-overrides ",alacritty:RGB"
set -as terminal-features ",alacritty:RGB"
set -sg escape-time 0
set -g base-index 1
setw -g pane-base-index 1
set -g renumber-windows on
#- UI -------------------------------------------------------------------------
set -g @primary-fg 'colour8'
set -g @primary-fg-active 'colour15'
set -g @primary-bg 'default'
set -g @accent-fg 'colour3'
set -g @accent-bg 'colour0'

set -g mouse on
set -g pane-border-style fg='#{@primary-fg}'
set -g pane-active-border-style fg='#{@primary-fg}'
set -g message-style 'bg=#{@primary-bg}  fg=#{@primary-fg}'
set -g window-status-current-style fg='#{@primary-fg}'
set -g window-status-activity-style fg='#{@accent-fg}'
set -g window-status-bell-style fg='#{@accent-fg}' 
set -g mode-style 'fg=#{@accent-fg}'
set -g status-style "bg=default fg=#{@primary-fg}"
set -g window-status-style "fg=#{@primary-fg}"
set -g window-status-current-style "fg=#{@primary-fg-active} bold"
set -g window-status-format "#W"
set -g window-status-current-format "#W"
set -g popup-border-style 'fg=#{@primary-fg}'
set -g popup-border-lines single

set -g status-left " "
set -g status-right "// #(kubectl config current-context 2>/dev/null || echo '-') #(~/.tmux/internet.sh) "
#- Keybinds -------------------------------------------------------------------

unbind C-b
set -g prefix C-s
bind x kill-pane
bind -n M-o select-pane -t :.+
bind -n M-O select-pane -t :.-
bind-key r command-prompt "rename-window '%%'"
bind-key -n M-e set-option -g status
bind s split-window -h -c "#{pane_current_path}"
bind o split-window -h -c "#{pane_current_path}"
bind v split-window -v -l 15 -c "#{pane_current_path}"
bind p split-window -v -c "#{pane_current_path}"
bind-key -n M-1 select-window -t 1
bind-key -n M-2 select-window -t 2
bind-key -n M-3 select-window -t 3
bind-key -n S-1 select-window -t 1
bind-key -n S-2 select-window -t 2
bind-key -n S-3 select-window -t 3
bind i if-shell '[ $(tmux list-windows -F "##{window_index}" | grep -cE "^(1|2|3)$") -eq 3 ]' \
    'display-message "Maximum windows (3) reached"' \
    'new-window -c "#{pane_current_path}"'
bind-key = run "if [ \$(tmux list-panes | wc -l) -le 2 ]; then tmux select-layout even-horizontal; else tmux select-layout tiled; fi"
bind -n M-k if-shell -F \
         '#{==:#{session_name},repl}' \
         { detach-client } \
         { popup -E -w40% -h100% -x 200% 'tmux attach -t repl || tmux new -s repl' }
