" -----------------------------------------
" Spartan config 
" -----------------------------------------

set nocompatible " Disable VI Compatibility
syntax on
filetype plugin indent on

set autoindent
set backspace=indent,eol,start
set formatoptions-=t              " Don't add line-breaks for lines over 'textwidth' chars
set hlsearch
set smartcase                     " ignore case unless I search specifically for uppercase
set nonumber
set nostartofline
set showmatch
set showcmd                       " bottom right of screen shows partially-typed commands i.e 'g'
set textwidth=80                  " 80 columns
set fillchars=vert:│
set belloff=all
set clipboard=unnamed,unnamedplus
set nobackup
set nowritebackup
set tabstop=4                     " Number of spaces <tab> counts for
set softtabstop=4
set shiftwidth=4
set expandtab                     " Space > Tabs
set colorcolumn=+1
set nowrap

" these affect the status line.. easier to just set the status line?
set showmode
set ruler

" prevent remaps
let g:omni_sql_no_default_maps = 1
let g:sh_noisk=1

if executable('rg') " N.B ripgrep searches all files by default
  set grepprg=rg\ --vimgrep\ --smart-case\ --follow
  set grepformat=%f:%l:%c:%m,%f:%l:%m
  command! -nargs=+ Grep execute 'silent grep! <q-args>'
endif

colorscheme spartan

cmap w!! w !sudo tee > /dev/null %
nnoremap Y y$
nnoremap <c-j> <c-w>j
nnoremap <c-k> <c-w>k
nnoremap <c-h> <c-w>h
nnoremap <c-l> <c-w>l
inoremap <c-l> <space>=><space>
inoremap <c-c> <esc>
nnoremap S <c-^>
nnoremap <c-q> :q<CR>
nnoremap <c-g> :noh<CR><c-g>
nnoremap gd <C-]> " check if this conflicts with vim-fireplace
nnoremap gD g<C-]>
nnoremap gi :e ~/.vimrc<CR>
nnoremap gn :lcd ~/.notes <bar> e ~/.notes/index.md<CR>
nnoremap ge :e <C-R>=fnamemodify(resolve(expand('%:p')), ':h') . '/'<CR>
nnoremap gs :Grep<space>
nnoremap gc :!ctags -R .<CR>
nnoremap gl :cclose<CR>
nnoremap Q @q
cnoremap        <C-A> <Home>
cnoremap        <C-B> <Left>
cnoremap <expr> <C-D> getcmdpos()>strlen(getcmdline())?"\<Lt>C-D>":"\<Lt>Del>"
cnoremap <expr> <C-F> getcmdpos()>strlen(getcmdline())?&cedit:"\<Lt>Right>"

augroup base
    autocmd!
    autocmd BufEnter * :syntax sync fromstart
    autocmd BufReadPost quickfix nnoremap <buffer> <CR> <CR>
    autocmd QuickFixCmdPost cgetexpr cwindow
    autocmd QuickFixCmdPost lgetexpr lwindow
    autocmd CmdwinEnter * nnoremap <buffer> <CR> <CR>
    autocmd FileType markdown setlocal nonumber
    autocmd FileType ruby,html,clojure setl ts=2 sw=2 sts=2
augroup END

function! SelectaCommand(choice_command, selecta_args, vim_command)
  try
    exec a:vim_command . " " . SelectaOutput(a:choice_command, a:selecta_args)
  catch /Vim:Interrupt/
    redraw!
    return
  endtry
endfunction

function! SelectaOutput(choice_command, selecta_args)
  let selection = system(a:choice_command . " | selecta " . a:selecta_args)
  let selection = substitute(selection, ' ', '\\ ', "g")
  redraw!
  return selection
endfunction

function! SelectaFile(path, glob, command)
  call SelectaCommand("fd -t f . " . a:path, "", a:command)
endfunction

nnoremap <space> :call SelectaFile(".", "*", ":edit")<cr>
